/**
 * parks-data.js
 * Master data source for all Trailmark park entries.
 * Cards are rendered dynamically by js/script.js.
 * This file is the source of truth for all park data.
 */

const BADGE_THEME_ART = {
  green: {
    outerFill: '#2D5016',
    skyFill: '#7ABDE8',
    groundFill: '#3D6B1F',
    detail: `
      <polygon points="100,36 156,128 44,128" fill="#8FAF72" />
      <polygon points="55,66 104,128 6,128" fill="#5C7A3E" />
      <polygon points="145,70 194,128 96,128" fill="#6B8E4E" />
      <polygon points="100,36 114,64 86,64" fill="#EDE9E0" />
      <polygon points="36,128 43,108 50,128" fill="#2D5016" />
      <rect x="39" y="128" width="7" height="9" fill="#2D5016" />
      <polygon points="150,128 157,110 164,128" fill="#2D5016" />
      <rect x="153" y="128" width="7" height="9" fill="#2D5016" />
    `,
    accentStroke: '#4A7A28',
  },
  blue: {
    outerFill: '#1A4A6B',
    skyFill: '#B8DEED',
    groundFill: '#3D6B1F',
    detail: `
      <ellipse cx="30" cy="155" rx="60" ry="24" fill="#4A7A2C" />
      <ellipse cx="170" cy="155" rx="60" ry="24" fill="#4A7A2C" />
      <ellipse cx="100" cy="148" rx="46" ry="18" fill="#096B6B" />
      <ellipse cx="100" cy="148" rx="34" ry="13" fill="#0F9090" />
      <ellipse cx="100" cy="148" rx="22" ry="8" fill="#20C0C0" />
      <ellipse cx="100" cy="148" rx="10" ry="4" fill="#60E0E0" />
      <ellipse cx="100" cy="118" rx="9" ry="20" fill="rgba(255,255,255,0.72)" />
      <ellipse cx="97" cy="97" rx="11" ry="20" fill="rgba(255,255,255,0.55)" />
      <ellipse cx="103" cy="77" rx="13" ry="22" fill="rgba(255,255,255,0.38)" />
      <ellipse cx="100" cy="57" rx="16" ry="22" fill="rgba(255,255,255,0.22)" />
    `,
    accentStroke: '#2A6A9B',
  },
  red: {
    outerFill: '#8B2210',
    skyFill: '#C9E8F5',
    groundFill: '#5A1508',
    detail: `
      <circle cx="100" cy="44" r="18" fill="#F5C518" />
      <rect x="0" y="82" width="200" height="14" fill="#D9A882" />
      <rect x="0" y="96" width="200" height="13" fill="#C9896A" />
      <rect x="0" y="109" width="200" height="13" fill="#B8633A" />
      <rect x="0" y="122" width="200" height="13" fill="#A0432A" />
      <rect x="0" y="135" width="200" height="13" fill="#8B2E1A" />
      <polygon points="0,82 42,62 74,82" fill="#D9A882" />
      <polygon points="126,82 158,60 200,82" fill="#D9A882" />
      <rect x="68" y="152" width="64" height="8" rx="4" fill="#4A90B8" />
    `,
    accentStroke: '#B03015',
  },
};

function buildBadgeSvgInner(parkId, badgeTheme) {
  const theme = BADGE_THEME_ART[badgeTheme] || BADGE_THEME_ART.green;
  const clipId = 'clip-' + parkId;

  return `
      <defs>
        <clipPath id="${clipId}">
          <circle cx="100" cy="100" r="82" />
        </clipPath>
      </defs>
      <circle cx="100" cy="100" r="97" fill="${theme.outerFill}" />
      <g clip-path="url(#${clipId})">
        <rect x="0" y="0" width="200" height="200" fill="${theme.skyFill}" />
        <rect x="0" y="128" width="200" height="72" fill="${theme.groundFill}" />
        ${theme.detail}
      </g>
      <circle cx="100" cy="100" r="82" fill="none" stroke="#F7F3EC" stroke-width="2" stroke-dasharray="5,4" />
      <circle cx="100" cy="100" r="89" fill="none" stroke="${theme.accentStroke}" stroke-width="1.5" />
    `;
}

function makePark(config) {
  return {
    id: config.id,
    name: config.name,
    state: config.state,
    region: config.region,
    npsCode: config.npsCode,
    timeZone: config.timeZone,
    shortDescription: config.shortDescription,
    landscape: config.landscape,
    badgeTheme: config.badgeTheme,
    status: config.status,
    ...(config.archiveSeq ? { archiveSeq: config.archiveSeq } : {}),
    futureSlug: config.futureSlug,
    ...(config.pageUrl ? { pageUrl: config.pageUrl } : {}),
    ...(config.heroFocus ? { heroFocus: config.heroFocus } : {}),
    art: {
      header: 'assets/park-art/' + config.id + '/header.webp',
      badge: 'assets/park-art/' + config.id + '/badge.webp',
      extra: 'assets/park-art/' + config.id + '/extra.webp',
    },
    svgInner: buildBadgeSvgInner(config.id, config.badgeTheme),
  };
}

const PARK_DEFINITIONS = [
  {
    id: 'yosemite',
    npsCode: 'yose',
    timeZone: 'America/Los_Angeles',
    name: 'Yosemite',
    state: 'California',
    region: 'West',
    landscape: 'mountain',
    shortDescription: 'Granite walls, sequoia groves, and high Sierra waterfalls gathered into one iconic valley.',
    badgeTheme: 'green',
    status: 'available',
    futureSlug: 'yosemite',
    pageUrl: 'parks/yosemite.html',
    archiveSeq: 1,
  },
  {
    id: 'yellowstone',
    npsCode: 'yell',
    timeZone: 'America/Denver',
    name: 'Yellowstone',
    state: 'Wyoming, Montana, Idaho',
    region: 'Mountain West',
    landscape: 'volcanic',
    shortDescription: 'Geyser basins, hot springs, and wide wildlife valleys across the high plateau.',
    badgeTheme: 'blue',
    status: 'available',
    futureSlug: 'yellowstone',
    pageUrl: 'parks/yellowstone.html',
    archiveSeq: 2,
  },
  {
    id: 'acadia',
    npsCode: 'acad',
    timeZone: 'America/New_York',
    name: 'Acadia',
    state: 'Maine',
    region: 'Northeast',
    landscape: 'coast/island',
    shortDescription: 'Granite peaks, evergreen forests, and Atlantic shoreline shaped by wind and fog.',
    badgeTheme: 'blue',
    status: 'available',
    futureSlug: 'acadia',
    pageUrl: 'parks/acadia.html',
    archiveSeq: 5,
    heroFocus: '62% 48%',
  },
  {
    id: 'american-samoa',
    npsCode: 'npsa',
    timeZone: 'Pacific/Pago_Pago',
    name: 'American Samoa',
    state: 'American Samoa',
    region: 'South Pacific',
    landscape: 'coast/island',
    shortDescription: 'Rainforest ridges, volcanic coast, and coral-fringed islands at the edge of the Pacific.',
    badgeTheme: 'blue',
    status: 'available',
    futureSlug: 'american-samoa',
    pageUrl: 'parks/american-samoa.html',
    archiveSeq: 28,
    heroFocus: '42% 62%',
  },
  {
    id: 'arches',
    npsCode: 'arch',
    timeZone: 'America/Denver',
    name: 'Arches',
    state: 'Utah',
    region: 'Southwest',
    landscape: 'desert',
    shortDescription: 'Delicate arches, sandstone fins, and balanced rock rising from high desert light.',
    badgeTheme: 'red',
    status: 'available',
    futureSlug: 'arches',
    pageUrl: 'parks/arches.html',
    archiveSeq: 11,
    heroFocus: '68% 42%',
  },
  {
    id: 'badlands',
    npsCode: 'badl',
    timeZone: 'America/Denver',
    name: 'Badlands',
    state: 'South Dakota',
    region: 'Great Plains',
    landscape: 'canyon',
    shortDescription: 'Striped buttes, fossil beds, and open prairie carved into stark geologic layers.',
    badgeTheme: 'red',
    status: 'available',
    futureSlug: 'badlands',
    pageUrl: 'parks/badlands.html',
    archiveSeq: 29,
    heroFocus: '62% 55%',
  },
  {
    id: 'big-bend',
    npsCode: 'bibe',
    timeZone: 'America/Chicago',
    name: 'Big Bend',
    state: 'Texas',
    region: 'Southwest',
    landscape: 'desert',
    shortDescription: 'Desert basins, river canyons, and mountain silhouettes along a remote border bend.',
    badgeTheme: 'red',
    status: 'available',
    futureSlug: 'big-bend',
    pageUrl: 'parks/big-bend.html',
    archiveSeq: 22,
    heroFocus: '50% 55%',
  },
  {
    id: 'biscayne',
    npsCode: 'bisc',
    timeZone: 'America/New_York',
    name: 'Biscayne',
    state: 'Florida',
    region: 'Southeast',
    landscape: 'coast/island',
    shortDescription: 'Mangrove shorelines, coral reefs, and turquoise shallows just beyond the mainland.',
    badgeTheme: 'blue',
    status: 'available',
    futureSlug: 'biscayne',
    pageUrl: 'parks/biscayne.html',
    archiveSeq: 30,
    heroFocus: '62% 52%',
  },
  {
    id: 'black-canyon-of-the-gunnison',
    npsCode: 'blca',
    timeZone: 'America/Denver',
    name: 'Black Canyon of the Gunnison',
    state: 'Colorado',
    region: 'Mountain West',
    landscape: 'canyon',
    shortDescription: 'Steep dark walls and narrow depths cut quickly by the Gunnison River.',
    badgeTheme: 'red',
    status: 'available',
    futureSlug: 'black-canyon-of-the-gunnison',
    pageUrl: 'parks/black-canyon-of-the-gunnison.html',
    archiveSeq: 24,
    heroFocus: '62% 48%',
  },
  {
    id: 'bryce-canyon',
    npsCode: 'brca',
    timeZone: 'America/Denver',
    name: 'Bryce Canyon',
    state: 'Utah',
    region: 'Southwest',
    landscape: 'canyon',
    shortDescription: 'Hoodoo amphitheaters glow in pink, orange, and gold across high plateau air.',
    badgeTheme: 'red',
    status: 'available',
    futureSlug: 'bryce-canyon',
    pageUrl: 'parks/bryce-canyon.html',
    archiveSeq: 10,
    heroFocus: '42% 58%',
  },
  {
    id: 'canyonlands',
    npsCode: 'cany',
    timeZone: 'America/Denver',
    name: 'Canyonlands',
    state: 'Utah',
    region: 'Southwest',
    landscape: 'canyon',
    shortDescription: 'Vast mesas and river-cut canyons unfolding into one of Utah\'s largest wild landscapes.',
    badgeTheme: 'red',
    status: 'available',
    futureSlug: 'canyonlands',
    pageUrl: 'parks/canyonlands.html',
    archiveSeq: 12,
    heroFocus: '40% 55%',
  },
  {
    id: 'capitol-reef',
    npsCode: 'care',
    timeZone: 'America/Denver',
    name: 'Capitol Reef',
    state: 'Utah',
    region: 'Southwest',
    landscape: 'canyon',
    shortDescription: 'Cliffs, domes, and orchards strung along the long warp of the Waterpocket Fold.',
    badgeTheme: 'red',
    status: 'available',
    futureSlug: 'capitol-reef',
    pageUrl: 'parks/capitol-reef.html',
    archiveSeq: 13,
    heroFocus: '72% 40%',
  },
  {
    id: 'carlsbad-caverns',
    npsCode: 'cave',
    timeZone: 'America/Denver',
    name: 'Carlsbad Caverns',
    state: 'New Mexico',
    region: 'Southwest',
    landscape: 'cave',
    shortDescription: 'Immense limestone chambers and desert ridges hiding one of the continent\'s great cave systems.',
    badgeTheme: 'blue',
    status: 'available',
    futureSlug: 'carlsbad-caverns',
    pageUrl: 'parks/carlsbad-caverns.html',
    archiveSeq: 20,
    heroFocus: '55% 58%',
  },
  {
    id: 'channel-islands',
    npsCode: 'chis',
    timeZone: 'America/Los_Angeles',
    name: 'Channel Islands',
    state: 'California',
    region: 'Pacific Coast',
    landscape: 'coast/island',
    shortDescription: 'Sea cliffs, island foxes, and kelp-rich waters set off the Southern California coast.',
    badgeTheme: 'blue',
    status: 'available',
    futureSlug: 'channel-islands',
    pageUrl: 'parks/channel-islands.html',
    archiveSeq: 31,
    heroFocus: '70% 55%',
  },
  {
    id: 'congaree',
    npsCode: 'cong',
    timeZone: 'America/New_York',
    name: 'Congaree',
    state: 'South Carolina',
    region: 'Southeast',
    landscape: 'wetland',
    shortDescription: 'Floodplain forest, towering hardwoods, and slow blackwater channels in the coastal plain.',
    badgeTheme: 'green',
    status: 'available',
    futureSlug: 'congaree',
    pageUrl: 'parks/congaree.html',
    archiveSeq: 32,
    heroFocus: '58% 48%',
  },
  {
    id: 'crater-lake',
    npsCode: 'crla',
    timeZone: 'America/Los_Angeles',
    name: 'Crater Lake',
    state: 'Oregon',
    region: 'Pacific Northwest',
    landscape: 'volcanic',
    shortDescription: 'A deep blue caldera lake ringed by cliffs and winter snow in southern Oregon.',
    badgeTheme: 'blue',
    status: 'available',
    futureSlug: 'crater-lake',
    pageUrl: 'parks/crater-lake.html',
    archiveSeq: 33,
    heroFocus: '50% 42%',
  },
  {
    id: 'cuyahoga-valley',
    npsCode: 'cuva',
    timeZone: 'America/New_York',
    name: 'Cuyahoga Valley',
    state: 'Ohio',
    region: 'Midwest',
    landscape: 'forest',
    shortDescription: 'Wooded ravines, winding river scenes, and restored meadows between Cleveland and Akron.',
    badgeTheme: 'green',
    status: 'available',
    futureSlug: 'cuyahoga-valley',
    pageUrl: 'parks/cuyahoga-valley.html',
    archiveSeq: 34,
    heroFocus: '62% 52%',
  },
  {
    id: 'death-valley',
    npsCode: 'deva',
    timeZone: 'America/Los_Angeles',
    name: 'Death Valley',
    state: 'California, Nevada',
    region: 'Southwest',
    landscape: 'desert',
    shortDescription: 'Salt flats, dune fields, and heat-shimmered basins stretching below mountain walls.',
    badgeTheme: 'red',
    status: 'available',
    futureSlug: 'death-valley',
    pageUrl: 'parks/death-valley.html',
    archiveSeq: 14,
    heroFocus: '62% 42%',
  },
  {
    id: 'denali',
    npsCode: 'dena',
    timeZone: 'America/Anchorage',
    name: 'Denali',
    state: 'Alaska',
    region: 'Alaska',
    landscape: 'mountain',
    shortDescription: 'Tundra valleys and immense alpine space anchored by North America\'s tallest peak.',
    badgeTheme: 'green',
    status: 'available',
    futureSlug: 'denali',
    pageUrl: 'parks/denali.html',
    archiveSeq: 35,
    heroFocus: '62% 40%',
  },
  {
    id: 'dry-tortugas',
    npsCode: 'drto',
    timeZone: 'America/New_York',
    name: 'Dry Tortugas',
    state: 'Florida',
    region: 'Caribbean',
    landscape: 'coast/island',
    shortDescription: 'Coral islands, clear water, and a massive coastal fort far beyond Key West.',
    badgeTheme: 'blue',
    status: 'available',
    futureSlug: 'dry-tortugas',
    pageUrl: 'parks/dry-tortugas.html',
    archiveSeq: 36,
    heroFocus: '50% 48%',
  },
  {
    id: 'everglades',
    npsCode: 'ever',
    timeZone: 'America/New_York',
    name: 'Everglades',
    state: 'Florida',
    region: 'Southeast',
    landscape: 'wetland',
    shortDescription: 'Sawgrass marsh, mangrove coast, and slow-moving water shaping a subtropical wilderness.',
    badgeTheme: 'green',
    status: 'available',
    futureSlug: 'everglades',
    pageUrl: 'parks/everglades.html',
    archiveSeq: 3,
  },
  {
    id: 'gates-of-the-arctic',
    npsCode: 'gaar',
    timeZone: 'America/Anchorage',
    name: 'Gates of the Arctic',
    state: 'Alaska',
    region: 'Alaska',
    landscape: 'arctic',
    shortDescription: 'Trackless tundra, mountain passes, and wild rivers above the Arctic Circle.',
    badgeTheme: 'blue',
    status: 'available',
    futureSlug: 'gates-of-the-arctic',
    pageUrl: 'parks/gates-of-the-arctic.html',
    archiveSeq: 37,
    heroFocus: '58% 42%',
  },
  {
    id: 'gateway-arch',
    npsCode: 'jeff',
    timeZone: 'America/Chicago',
    name: 'Gateway Arch',
    state: 'Missouri',
    region: 'Midwest',
    landscape: 'forest',
    shortDescription: 'A riverfront monument and civic landscape marking westward expansion at St. Louis.',
    badgeTheme: 'blue',
    status: 'available',
    futureSlug: 'gateway-arch',
    pageUrl: 'parks/gateway-arch.html',
    archiveSeq: 38,
    heroFocus: '52% 40%',
  },
  {
    id: 'glacier',
    npsCode: 'glac',
    timeZone: 'America/Denver',
    name: 'Glacier',
    state: 'Montana',
    region: 'Mountain West',
    landscape: 'mountain',
    shortDescription: 'Alpine lakes, glacial valleys, and dramatic ridgelines on the northern Rockies spine.',
    badgeTheme: 'green',
    status: 'available',
    futureSlug: 'glacier',
    pageUrl: 'parks/glacier.html',
    archiveSeq: 8,
    heroFocus: '58% 42%',
  },
  {
    id: 'glacier-bay',
    npsCode: 'glba',
    timeZone: 'America/Anchorage',
    name: 'Glacier Bay',
    state: 'Alaska',
    region: 'Alaska',
    landscape: 'coast/island',
    shortDescription: 'Tidewater glaciers, icy fjords, and forested islands along Alaska\'s southeastern coast.',
    badgeTheme: 'blue',
    status: 'available',
    futureSlug: 'glacier-bay',
    pageUrl: 'parks/glacier-bay.html',
    archiveSeq: 39,
    heroFocus: '48% 55%',
  },
  {
    id: 'grand-canyon',
    npsCode: 'grca',
    timeZone: 'America/Phoenix',
    name: 'Grand Canyon',
    state: 'Arizona',
    region: 'Southwest',
    landscape: 'canyon',
    shortDescription: 'Layered canyon walls and river depth revealing one of Earth\'s grandest geologic stories.',
    badgeTheme: 'red',
    status: 'available',
    futureSlug: 'grand-canyon',
    pageUrl: 'parks/grand-canyon.html',
    archiveSeq: 4,
    heroFocus: '42% 58%',
  },
  {
    id: 'grand-teton',
    npsCode: 'grte',
    timeZone: 'America/Denver',
    name: 'Grand Teton',
    state: 'Wyoming',
    region: 'Mountain West',
    landscape: 'mountain',
    shortDescription: 'Jagged peaks, sage flats, and reflective lakes beneath the Teton Range.',
    badgeTheme: 'green',
    status: 'available',
    futureSlug: 'grand-teton',
    pageUrl: 'parks/grand-teton.html',
    archiveSeq: 27,
    heroFocus: '50% 38%',
  },
  {
    id: 'great-basin',
    npsCode: 'grba',
    timeZone: 'America/Los_Angeles',
    name: 'Great Basin',
    state: 'Nevada',
    region: 'Great Basin',
    landscape: 'mountain',
    shortDescription: 'Ancient bristlecones, limestone caves, and high desert peaks under dark western skies.',
    badgeTheme: 'green',
    status: 'available',
    futureSlug: 'great-basin',
    pageUrl: 'parks/great-basin.html',
    archiveSeq: 26,
    heroFocus: '74% 50%',
  },
  {
    id: 'great-sand-dunes',
    npsCode: 'grsa',
    timeZone: 'America/Denver',
    name: 'Great Sand Dunes',
    state: 'Colorado',
    region: 'Mountain West',
    landscape: 'desert',
    shortDescription: 'Towering dunes rise against alpine backdrops, wetlands, and broad San Luis light.',
    badgeTheme: 'red',
    status: 'available',
    futureSlug: 'great-sand-dunes',
    pageUrl: 'parks/great-sand-dunes.html',
    archiveSeq: 18,
    heroFocus: '52% 48%',
  },
  {
    id: 'great-smoky-mountains',
    npsCode: 'grsm',
    timeZone: 'America/New_York',
    name: 'Great Smoky Mountains',
    state: 'Tennessee, North Carolina',
    region: 'Southeast',
    landscape: 'forest',
    shortDescription: 'Blue ridges, old-growth forests, and mist-softened hollows along the Appalachian crest.',
    badgeTheme: 'green',
    status: 'available',
    futureSlug: 'great-smoky-mountains',
    pageUrl: 'parks/great-smoky-mountains.html',
    archiveSeq: 9,
    heroFocus: '48% 46%',
  },
  {
    id: 'guadalupe-mountains',
    npsCode: 'gumo',
    timeZone: 'America/Denver',
    name: 'Guadalupe Mountains',
    state: 'Texas',
    region: 'Southwest',
    landscape: 'desert',
    shortDescription: 'Fossil reefs, desert trails, and high Texas peaks rising from the Chihuahuan Basin.',
    badgeTheme: 'red',
    status: 'available',
    futureSlug: 'guadalupe-mountains',
    pageUrl: 'parks/guadalupe-mountains.html',
    archiveSeq: 21,
    heroFocus: '68% 46%',
  },
  {
    id: 'haleakala',
    npsCode: 'hale',
    timeZone: 'Pacific/Honolulu',
    name: 'Haleakala',
    state: 'Hawaii',
    region: 'Hawaii',
    landscape: 'volcanic',
    shortDescription: 'Volcanic summit landscapes and rainforest coast woven together on the island of Maui.',
    badgeTheme: 'red',
    status: 'available',
    futureSlug: 'haleakala',
    pageUrl: 'parks/haleakala.html',
    archiveSeq: 40,
    heroFocus: '68% 58%',
  },
  {
    id: 'hawaii-volcanoes',
    npsCode: 'havo',
    timeZone: 'Pacific/Honolulu',
    name: 'Hawaii Volcanoes',
    state: 'Hawaii',
    region: 'Hawaii',
    landscape: 'volcanic',
    shortDescription: 'Lava fields, crater rims, and active volcanic forces shaping the Big Island.',
    badgeTheme: 'red',
    status: 'available',
    futureSlug: 'hawaii-volcanoes',
    pageUrl: 'parks/hawaii-volcanoes.html',
    archiveSeq: 41,
    heroFocus: '62% 58%',
  },
  {
    id: 'hot-springs',
    npsCode: 'hosp',
    timeZone: 'America/Chicago',
    name: 'Hot Springs',
    state: 'Arkansas',
    region: 'South',
    landscape: 'forest',
    shortDescription: 'Historic bathhouses and thermal springs set against forested hills in central Arkansas.',
    badgeTheme: 'blue',
    status: 'available',
    futureSlug: 'hot-springs',
    pageUrl: 'parks/hot-springs.html',
    archiveSeq: 42,
    heroFocus: '62% 52%',
  },
  {
    id: 'indiana-dunes',
    npsCode: 'indu',
    timeZone: 'America/Chicago',
    name: 'Indiana Dunes',
    state: 'Indiana',
    region: 'Midwest',
    landscape: 'coast/island',
    shortDescription: 'Lake Michigan shore, shifting dunes, and rich habitat packed into a narrow coast.',
    badgeTheme: 'blue',
    status: 'available',
    futureSlug: 'indiana-dunes',
    pageUrl: 'parks/indiana-dunes.html',
    archiveSeq: 43,
    heroFocus: '38% 58%',
  },
  {
    id: 'isle-royale',
    npsCode: 'isro',
    timeZone: 'America/New_York',
    name: 'Isle Royale',
    state: 'Michigan',
    region: 'Great Lakes',
    landscape: 'coast/island',
    shortDescription: 'Remote island wilderness, inland lakes, and long trails deep in Lake Superior.',
    badgeTheme: 'blue',
    status: 'available',
    futureSlug: 'isle-royale',
    pageUrl: 'parks/isle-royale.html',
    archiveSeq: 44,
    heroFocus: '48% 52%',
  },
  {
    id: 'joshua-tree',
    npsCode: 'jotr',
    timeZone: 'America/Los_Angeles',
    name: 'Joshua Tree',
    state: 'California',
    region: 'Southwest',
    landscape: 'desert',
    shortDescription: 'Boulder piles, desert trees, and stark sky where the Mojave meets the Colorado.',
    badgeTheme: 'red',
    status: 'available',
    futureSlug: 'joshua-tree',
    pageUrl: 'parks/joshua-tree.html',
    archiveSeq: 15,
    heroFocus: '74% 46%',
  },
  {
    id: 'katmai',
    npsCode: 'katm',
    timeZone: 'America/Anchorage',
    name: 'Katmai',
    state: 'Alaska',
    region: 'Alaska',
    landscape: 'volcanic',
    shortDescription: 'Brown bears, volcanic valleys, and salmon-rich rivers on Alaska\'s wild coast.',
    badgeTheme: 'green',
    status: 'available',
    futureSlug: 'katmai',
    pageUrl: 'parks/katmai.html',
    archiveSeq: 45,
    heroFocus: '52% 48%',
  },
  {
    id: 'kenai-fjords',
    npsCode: 'kefj',
    timeZone: 'America/Anchorage',
    name: 'Kenai Fjords',
    state: 'Alaska',
    region: 'Alaska',
    landscape: 'coast/island',
    shortDescription: 'Glacier-fed fjords, marine wildlife, and icefields pressing toward the sea.',
    badgeTheme: 'blue',
    status: 'available',
    futureSlug: 'kenai-fjords',
    pageUrl: 'parks/kenai-fjords.html',
    archiveSeq: 46,
    heroFocus: '58% 52%',
  },
  {
    id: 'kings-canyon',
    npsCode: 'seki',
    timeZone: 'America/Los_Angeles',
    name: 'Kings Canyon',
    state: 'California',
    region: 'West',
    landscape: 'canyon',
    shortDescription: 'Deep canyon walls, giant sequoias, and high Sierra country beyond the foothills.',
    badgeTheme: 'green',
    status: 'available',
    futureSlug: 'kings-canyon',
    pageUrl: 'parks/kings-canyon.html',
    archiveSeq: 47,
    heroFocus: '46% 55%',
  },
  {
    id: 'kobuk-valley',
    npsCode: 'kova',
    timeZone: 'America/Anchorage',
    name: 'Kobuk Valley',
    state: 'Alaska',
    region: 'Alaska',
    landscape: 'arctic',
    shortDescription: 'Arctic dunes, winding rivers, and caribou migration across a roadless northern valley.',
    badgeTheme: 'blue',
    status: 'available',
    futureSlug: 'kobuk-valley',
    pageUrl: 'parks/kobuk-valley.html',
    archiveSeq: 48,
    heroFocus: '66% 62%',
  },
  {
    id: 'lake-clark',
    npsCode: 'lacl',
    timeZone: 'America/Anchorage',
    name: 'Lake Clark',
    state: 'Alaska',
    region: 'Alaska',
    landscape: 'volcanic',
    shortDescription: 'Volcanoes, salmon streams, and vast lakes joining coast, tundra, and mountains.',
    badgeTheme: 'blue',
    status: 'available',
    futureSlug: 'lake-clark',
    pageUrl: 'parks/lake-clark.html',
    archiveSeq: 49,
    heroFocus: '64% 44%',
  },
  {
    id: 'lassen-volcanic',
    npsCode: 'lavo',
    timeZone: 'America/Los_Angeles',
    name: 'Lassen Volcanic',
    state: 'California',
    region: 'West',
    landscape: 'volcanic',
    shortDescription: 'Steam vents, cinder cones, and alpine forests clustered around an active volcanic field.',
    badgeTheme: 'red',
    status: 'available',
    futureSlug: 'lassen-volcanic',
    pageUrl: 'parks/lassen-volcanic.html',
    archiveSeq: 50,
    heroFocus: '58% 46%',
  },
  {
    id: 'mammoth-cave',
    npsCode: 'maca',
    timeZone: 'America/Chicago',
    name: 'Mammoth Cave',
    state: 'Kentucky',
    region: 'Southeast',
    landscape: 'cave',
    shortDescription: 'Long cave passages and green river hills shelter the world\'s longest known cave.',
    badgeTheme: 'blue',
    status: 'available',
    futureSlug: 'mammoth-cave',
    pageUrl: 'parks/mammoth-cave.html',
    archiveSeq: 51,
    heroFocus: '56% 52%',
  },
  {
    id: 'mesa-verde',
    npsCode: 'meve',
    timeZone: 'America/Denver',
    name: 'Mesa Verde',
    state: 'Colorado',
    region: 'Southwest',
    landscape: 'canyon',
    shortDescription: 'Cliff dwellings and mesa-top sites preserving centuries of Ancestral Pueblo history.',
    badgeTheme: 'red',
    status: 'available',
    futureSlug: 'mesa-verde',
    pageUrl: 'parks/mesa-verde.html',
    archiveSeq: 23,
    heroFocus: '70% 46%',
  },
  {
    id: 'mount-rainier',
    npsCode: 'mora',
    timeZone: 'America/Los_Angeles',
    name: 'Mount Rainier',
    state: 'Washington',
    region: 'Pacific Northwest',
    landscape: 'volcanic',
    shortDescription: 'Glacier slopes, wildflower meadows, and a singular stratovolcano dominating the horizon.',
    badgeTheme: 'green',
    status: 'available',
    futureSlug: 'mount-rainier',
    pageUrl: 'parks/mount-rainier.html',
    archiveSeq: 52,
    heroFocus: '50% 42%',
  },
  {
    id: 'new-river-gorge',
    npsCode: 'neri',
    timeZone: 'America/New_York',
    name: 'New River Gorge',
    state: 'West Virginia',
    region: 'Appalachia',
    landscape: 'canyon',
    shortDescription: 'Deep forested gorge, sandstone cliffs, and a free-flowing river through southern West Virginia.',
    badgeTheme: 'green',
    status: 'available',
    futureSlug: 'new-river-gorge',
    pageUrl: 'parks/new-river-gorge.html',
    archiveSeq: 53,
    heroFocus: '58% 42%',
  },
  {
    id: 'north-cascades',
    npsCode: 'noca',
    timeZone: 'America/Los_Angeles',
    name: 'North Cascades',
    state: 'Washington',
    region: 'Pacific Northwest',
    landscape: 'mountain',
    shortDescription: 'Jagged summits, glaciers, and dense evergreen valleys across Washington\'s northern range.',
    badgeTheme: 'green',
    status: 'available',
    futureSlug: 'north-cascades',
    pageUrl: 'parks/north-cascades.html',
    archiveSeq: 54,
    heroFocus: '62% 46%',
  },
  {
    id: 'olympic',
    npsCode: 'olym',
    timeZone: 'America/Los_Angeles',
    name: 'Olympic',
    state: 'Washington',
    region: 'Pacific Northwest',
    landscape: 'forest',
    shortDescription: 'Rainforest, glacier-capped mountains, and wild Pacific beaches on one peninsula.',
    badgeTheme: 'green',
    status: 'available',
    futureSlug: 'olympic',
    pageUrl: 'parks/olympic.html',
    archiveSeq: 7,
    heroFocus: '55% 48%',
  },
  {
    id: 'petrified-forest',
    npsCode: 'pefo',
    timeZone: 'America/Phoenix',
    name: 'Petrified Forest',
    state: 'Arizona',
    region: 'Southwest',
    landscape: 'desert',
    shortDescription: 'Painted Desert color and ancient fossil logs scattered across open high desert.',
    badgeTheme: 'red',
    status: 'available',
    futureSlug: 'petrified-forest',
    pageUrl: 'parks/petrified-forest.html',
    archiveSeq: 17,
    heroFocus: '58% 68%',
  },
  {
    id: 'pinnacles',
    npsCode: 'pinn',
    timeZone: 'America/Los_Angeles',
    name: 'Pinnacles',
    state: 'California',
    region: 'West',
    landscape: 'volcanic',
    shortDescription: 'Spired volcanic rock, chaparral hills, and condor country in inland California.',
    badgeTheme: 'red',
    status: 'available',
    futureSlug: 'pinnacles',
    pageUrl: 'parks/pinnacles.html',
    archiveSeq: 55,
    heroFocus: '54% 48%',
  },
  {
    id: 'redwood',
    npsCode: 'redw',
    timeZone: 'America/Los_Angeles',
    name: 'Redwood',
    state: 'California',
    region: 'Pacific Coast',
    landscape: 'forest',
    shortDescription: 'Towering redwoods, fern canyons, and fog-softened coast along northern California.',
    badgeTheme: 'green',
    status: 'available',
    futureSlug: 'redwood',
    pageUrl: 'parks/redwood.html',
    archiveSeq: 56,
    heroFocus: '62% 55%',
  },
  {
    id: 'rocky-mountain',
    npsCode: 'romo',
    timeZone: 'America/Denver',
    name: 'Rocky Mountain',
    state: 'Colorado',
    region: 'Mountain West',
    landscape: 'mountain',
    shortDescription: 'Alpine tundra, high lakes, and sweeping ridgelines across the central Rockies.',
    badgeTheme: 'green',
    status: 'available',
    futureSlug: 'rocky-mountain',
    pageUrl: 'parks/rocky-mountain.html',
    archiveSeq: 25,
    heroFocus: '56% 38%',
  },
  {
    id: 'saguaro',
    npsCode: 'sagu',
    timeZone: 'America/Phoenix',
    name: 'Saguaro',
    state: 'Arizona',
    region: 'Southwest',
    landscape: 'desert',
    shortDescription: 'Iconic cactus forests and Sonoran desert light framing the edges of Tucson.',
    badgeTheme: 'red',
    status: 'available',
    futureSlug: 'saguaro',
    pageUrl: 'parks/saguaro.html',
    archiveSeq: 16,
    heroFocus: '64% 50%',
  },
  {
    id: 'sequoia',
    npsCode: 'seki',
    timeZone: 'America/Los_Angeles',
    name: 'Sequoia',
    state: 'California',
    region: 'West',
    landscape: 'forest',
    shortDescription: 'Massive trees, granite country, and high Sierra wilderness beyond giant groves.',
    badgeTheme: 'green',
    status: 'available',
    futureSlug: 'sequoia',
    pageUrl: 'parks/sequoia.html',
    archiveSeq: 57,
    heroFocus: '56% 60%',
  },
  {
    id: 'shenandoah',
    npsCode: 'shen',
    timeZone: 'America/New_York',
    name: 'Shenandoah',
    state: 'Virginia',
    region: 'Appalachia',
    landscape: 'forest',
    shortDescription: 'Blue Ridge overlooks, wooded hollows, and long skyline drives above the valley.',
    badgeTheme: 'green',
    status: 'available',
    futureSlug: 'shenandoah',
    pageUrl: 'parks/shenandoah.html',
    archiveSeq: 58,
    heroFocus: '62% 48%',
  },
  {
    id: 'theodore-roosevelt',
    npsCode: 'thro',
    timeZone: 'America/Denver',
    name: 'Theodore Roosevelt',
    state: 'North Dakota',
    region: 'Great Plains',
    landscape: 'canyon',
    shortDescription: 'Badlands, prairie, and bison country honoring a president shaped by this landscape.',
    badgeTheme: 'red',
    status: 'available',
    futureSlug: 'theodore-roosevelt',
    pageUrl: 'parks/theodore-roosevelt.html',
    archiveSeq: 59,
    heroFocus: '58% 52%',
  },
  {
    id: 'virgin-islands',
    npsCode: 'viis',
    timeZone: 'America/St_Thomas',
    name: 'Virgin Islands',
    state: 'U.S. Virgin Islands',
    region: 'Caribbean',
    landscape: 'coast/island',
    shortDescription: 'White-sand bays, coral waters, and tropical hills across St. John and St. Thomas.',
    badgeTheme: 'blue',
    status: 'available',
    futureSlug: 'virgin-islands',
    pageUrl: 'parks/virgin-islands.html',
    archiveSeq: 60,
    heroFocus: '42% 55%',
  },
  {
    id: 'voyageurs',
    npsCode: 'voya',
    timeZone: 'America/Chicago',
    name: 'Voyageurs',
    state: 'Minnesota',
    region: 'Great Lakes',
    landscape: 'wetland',
    shortDescription: 'Island-dotted lakes, boreal forest, and canoe routes along the northern border.',
    badgeTheme: 'blue',
    status: 'available',
    futureSlug: 'voyageurs',
    pageUrl: 'parks/voyageurs.html',
    archiveSeq: 61,
    heroFocus: '68% 62%',
  },
  {
    id: 'white-sands',
    npsCode: 'whsa',
    timeZone: 'America/Denver',
    name: 'White Sands',
    state: 'New Mexico',
    region: 'Southwest',
    landscape: 'desert',
    shortDescription: 'Brilliant gypsum dunes rolling in white waves across a broad desert basin.',
    badgeTheme: 'blue',
    status: 'available',
    futureSlug: 'white-sands',
    pageUrl: 'parks/white-sands.html',
    archiveSeq: 19,
    heroFocus: '58% 62%',
  },
  {
    id: 'wind-cave',
    npsCode: 'wica',
    timeZone: 'America/Denver',
    name: 'Wind Cave',
    state: 'South Dakota',
    region: 'Great Plains',
    landscape: 'cave',
    shortDescription: 'Mixed-grass prairie above and intricate cave passage below in the Black Hills.',
    badgeTheme: 'green',
    status: 'available',
    futureSlug: 'wind-cave',
    pageUrl: 'parks/wind-cave.html',
    archiveSeq: 62,
    heroFocus: '50% 62%',
  },
  {
    id: 'wrangell-st-elias',
    npsCode: 'wrst',
    timeZone: 'America/Anchorage',
    name: 'Wrangell-St. Elias',
    state: 'Alaska',
    region: 'Alaska',
    landscape: 'mountain',
    shortDescription: 'Immense glaciers, giant peaks, and raw scale across America\'s largest national park.',
    badgeTheme: 'blue',
    status: 'available',
    futureSlug: 'wrangell-st-elias',
    pageUrl: 'parks/wrangell-st-elias.html',
    archiveSeq: 63,
    heroFocus: '72% 42%',
  },
  {
    id: 'zion',
    npsCode: 'zion',
    timeZone: 'America/Denver',
    name: 'Zion',
    state: 'Utah',
    region: 'Southwest',
    landscape: 'canyon',
    shortDescription: 'Sheer canyon walls, hanging gardens, and desert river pathways in southern Utah.',
    badgeTheme: 'red',
    status: 'available',
    futureSlug: 'zion',
    pageUrl: 'parks/zion.html',
    archiveSeq: 6,
    heroFocus: '62% 46%',
  },
];

const PARKS = PARK_DEFINITIONS.map(makePark);
