/**
 * parks-data.js
 * Master data source for all Trailmark park entries.
 * Cards are rendered dynamically by js/script.js.
 * This file is the source of truth for all park data.
 */

const BADGE_THEME_ART = {
  green: {
    outerFill: '#2D5016',
    skyFill: '#7ABDE8',
    groundFill: '#3D6B1F',
    detail: `
      <polygon points="100,36 156,128 44,128" fill="#8FAF72" />
      <polygon points="55,66 104,128 6,128" fill="#5C7A3E" />
      <polygon points="145,70 194,128 96,128" fill="#6B8E4E" />
      <polygon points="100,36 114,64 86,64" fill="#EDE9E0" />
      <polygon points="36,128 43,108 50,128" fill="#2D5016" />
      <rect x="39" y="128" width="7" height="9" fill="#2D5016" />
      <polygon points="150,128 157,110 164,128" fill="#2D5016" />
      <rect x="153" y="128" width="7" height="9" fill="#2D5016" />
    `,
    accentStroke: '#4A7A28',
  },
  blue: {
    outerFill: '#1A4A6B',
    skyFill: '#B8DEED',
    groundFill: '#3D6B1F',
    detail: `
      <ellipse cx="30" cy="155" rx="60" ry="24" fill="#4A7A2C" />
      <ellipse cx="170" cy="155" rx="60" ry="24" fill="#4A7A2C" />
      <ellipse cx="100" cy="148" rx="46" ry="18" fill="#096B6B" />
      <ellipse cx="100" cy="148" rx="34" ry="13" fill="#0F9090" />
      <ellipse cx="100" cy="148" rx="22" ry="8" fill="#20C0C0" />
      <ellipse cx="100" cy="148" rx="10" ry="4" fill="#60E0E0" />
      <ellipse cx="100" cy="118" rx="9" ry="20" fill="rgba(255,255,255,0.72)" />
      <ellipse cx="97" cy="97" rx="11" ry="20" fill="rgba(255,255,255,0.55)" />
      <ellipse cx="103" cy="77" rx="13" ry="22" fill="rgba(255,255,255,0.38)" />
      <ellipse cx="100" cy="57" rx="16" ry="22" fill="rgba(255,255,255,0.22)" />
    `,
    accentStroke: '#2A6A9B',
  },
  red: {
    outerFill: '#8B2210',
    skyFill: '#C9E8F5',
    groundFill: '#5A1508',
    detail: `
      <circle cx="100" cy="44" r="18" fill="#F5C518" />
      <rect x="0" y="82" width="200" height="14" fill="#D9A882" />
      <rect x="0" y="96" width="200" height="13" fill="#C9896A" />
      <rect x="0" y="109" width="200" height="13" fill="#B8633A" />
      <rect x="0" y="122" width="200" height="13" fill="#A0432A" />
      <rect x="0" y="135" width="200" height="13" fill="#8B2E1A" />
      <polygon points="0,82 42,62 74,82" fill="#D9A882" />
      <polygon points="126,82 158,60 200,82" fill="#D9A882" />
      <rect x="68" y="152" width="64" height="8" rx="4" fill="#4A90B8" />
    `,
    accentStroke: '#B03015',
  },
};

function buildBadgeSvgInner(parkId, badgeTheme) {
  const theme = BADGE_THEME_ART[badgeTheme] || BADGE_THEME_ART.green;
  const clipId = 'clip-' + parkId;

  return `
      <defs>
        <clipPath id="${clipId}">
          <circle cx="100" cy="100" r="82" />
        </clipPath>
      </defs>
      <circle cx="100" cy="100" r="97" fill="${theme.outerFill}" />
      <g clip-path="url(#${clipId})">
        <rect x="0" y="0" width="200" height="200" fill="${theme.skyFill}" />
        <rect x="0" y="128" width="200" height="72" fill="${theme.groundFill}" />
        ${theme.detail}
      </g>
      <circle cx="100" cy="100" r="82" fill="none" stroke="#F7F3EC" stroke-width="2" stroke-dasharray="5,4" />
      <circle cx="100" cy="100" r="89" fill="none" stroke="${theme.accentStroke}" stroke-width="1.5" />
    `;
}

function makePark(config) {
  return {
    id: config.id,
    name: config.name,
    state: config.state,
    region: config.region,
    shortDescription: config.shortDescription,
    badgeTheme: config.badgeTheme,
    status: config.status,
    futureSlug: config.futureSlug,
    ...(config.pageUrl ? { pageUrl: config.pageUrl } : {}),
    svgInner: buildBadgeSvgInner(config.id, config.badgeTheme),
  };
}

const PARK_DEFINITIONS = [
  {
    id: 'yosemite',
    name: 'Yosemite',
    state: 'California',
    region: 'West',
    shortDescription: 'Granite walls, sequoia groves, and high Sierra waterfalls gathered into one iconic valley.',
    badgeTheme: 'green',
    status: 'available',
    futureSlug: 'yosemite',
    pageUrl: 'parks/yosemite.html',
  },
  {
    id: 'yellowstone',
    name: 'Yellowstone',
    state: 'Wyoming, Montana, Idaho',
    region: 'Mountain West',
    shortDescription: 'Geyser basins, hot springs, and wide wildlife valleys across the high plateau.',
    badgeTheme: 'blue',
    status: 'available',
    futureSlug: 'yellowstone',
    pageUrl: 'parks/yellowstone.html',
  },
  {
    id: 'acadia',
    name: 'Acadia',
    state: 'Maine',
    region: 'Northeast',
    shortDescription: 'Granite peaks, evergreen forests, and Atlantic shoreline shaped by wind and fog.',
    badgeTheme: 'blue',
    status: 'in-progress',
    futureSlug: 'acadia',
  },
  {
    id: 'american-samoa',
    name: 'American Samoa',
    state: 'American Samoa',
    region: 'South Pacific',
    shortDescription: 'Rainforest ridges, volcanic coast, and coral-fringed islands at the edge of the Pacific.',
    badgeTheme: 'blue',
    status: 'in-progress',
    futureSlug: 'american-samoa',
  },
  {
    id: 'arches',
    name: 'Arches',
    state: 'Utah',
    region: 'Southwest',
    shortDescription: 'Delicate arches, sandstone fins, and balanced rock rising from high desert light.',
    badgeTheme: 'red',
    status: 'in-progress',
    futureSlug: 'arches',
  },
  {
    id: 'badlands',
    name: 'Badlands',
    state: 'South Dakota',
    region: 'Great Plains',
    shortDescription: 'Striped buttes, fossil beds, and open prairie carved into stark geologic layers.',
    badgeTheme: 'red',
    status: 'in-progress',
    futureSlug: 'badlands',
  },
  {
    id: 'big-bend',
    name: 'Big Bend',
    state: 'Texas',
    region: 'Southwest',
    shortDescription: 'Desert basins, river canyons, and mountain silhouettes along a remote border bend.',
    badgeTheme: 'red',
    status: 'in-progress',
    futureSlug: 'big-bend',
  },
  {
    id: 'biscayne',
    name: 'Biscayne',
    state: 'Florida',
    region: 'Southeast',
    shortDescription: 'Mangrove shorelines, coral reefs, and turquoise shallows just beyond the mainland.',
    badgeTheme: 'blue',
    status: 'in-progress',
    futureSlug: 'biscayne',
  },
  {
    id: 'black-canyon-of-the-gunnison',
    name: 'Black Canyon of the Gunnison',
    state: 'Colorado',
    region: 'Mountain West',
    shortDescription: 'Steep dark walls and narrow depths cut quickly by the Gunnison River.',
    badgeTheme: 'red',
    status: 'in-progress',
    futureSlug: 'black-canyon-of-the-gunnison',
  },
  {
    id: 'bryce-canyon',
    name: 'Bryce Canyon',
    state: 'Utah',
    region: 'Southwest',
    shortDescription: 'Hoodoo amphitheaters glow in pink, orange, and gold across high plateau air.',
    badgeTheme: 'red',
    status: 'in-progress',
    futureSlug: 'bryce-canyon',
  },
  {
    id: 'canyonlands',
    name: 'Canyonlands',
    state: 'Utah',
    region: 'Southwest',
    shortDescription: 'Vast mesas and river-cut canyons unfolding into one of Utahs largest wild landscapes.',
    badgeTheme: 'red',
    status: 'in-progress',
    futureSlug: 'canyonlands',
  },
  {
    id: 'capitol-reef',
    name: 'Capitol Reef',
    state: 'Utah',
    region: 'Southwest',
    shortDescription: 'Cliffs, domes, and orchards strung along the long warp of the Waterpocket Fold.',
    badgeTheme: 'red',
    status: 'in-progress',
    futureSlug: 'capitol-reef',
  },
  {
    id: 'carlsbad-caverns',
    name: 'Carlsbad Caverns',
    state: 'New Mexico',
    region: 'Southwest',
    shortDescription: 'Immense limestone chambers and desert ridges hiding one of the continents great cave systems.',
    badgeTheme: 'blue',
    status: 'in-progress',
    futureSlug: 'carlsbad-caverns',
  },
  {
    id: 'channel-islands',
    name: 'Channel Islands',
    state: 'California',
    region: 'Pacific Coast',
    shortDescription: 'Sea cliffs, island foxes, and kelp-rich waters set off the Southern California coast.',
    badgeTheme: 'blue',
    status: 'in-progress',
    futureSlug: 'channel-islands',
  },
  {
    id: 'congaree',
    name: 'Congaree',
    state: 'South Carolina',
    region: 'Southeast',
    shortDescription: 'Floodplain forest, towering hardwoods, and slow blackwater channels in the coastal plain.',
    badgeTheme: 'green',
    status: 'in-progress',
    futureSlug: 'congaree',
  },
  {
    id: 'crater-lake',
    name: 'Crater Lake',
    state: 'Oregon',
    region: 'Pacific Northwest',
    shortDescription: 'A deep blue caldera lake ringed by cliffs and winter snow in southern Oregon.',
    badgeTheme: 'blue',
    status: 'in-progress',
    futureSlug: 'crater-lake',
  },
  {
    id: 'cuyahoga-valley',
    name: 'Cuyahoga Valley',
    state: 'Ohio',
    region: 'Midwest',
    shortDescription: 'Wooded ravines, winding river scenes, and restored meadows between Cleveland and Akron.',
    badgeTheme: 'green',
    status: 'in-progress',
    futureSlug: 'cuyahoga-valley',
  },
  {
    id: 'death-valley',
    name: 'Death Valley',
    state: 'California, Nevada',
    region: 'Southwest',
    shortDescription: 'Salt flats, dune fields, and heat-shimmered basins stretching below mountain walls.',
    badgeTheme: 'red',
    status: 'in-progress',
    futureSlug: 'death-valley',
  },
  {
    id: 'denali',
    name: 'Denali',
    state: 'Alaska',
    region: 'Alaska',
    shortDescription: 'Tundra valleys and immense alpine space anchored by North Americas tallest peak.',
    badgeTheme: 'green',
    status: 'in-progress',
    futureSlug: 'denali',
  },
  {
    id: 'dry-tortugas',
    name: 'Dry Tortugas',
    state: 'Florida',
    region: 'Caribbean',
    shortDescription: 'Coral islands, clear water, and a massive coastal fort far beyond Key West.',
    badgeTheme: 'blue',
    status: 'in-progress',
    futureSlug: 'dry-tortugas',
  },
  {
    id: 'everglades',
    name: 'Everglades',
    state: 'Florida',
    region: 'Southeast',
    shortDescription: 'Sawgrass marsh, mangrove coast, and slow-moving water shaping a subtropical wilderness.',
    badgeTheme: 'green',
    status: 'available',
    futureSlug: 'everglades',
    pageUrl: 'parks/everglades.html',
  },
  {
    id: 'gates-of-the-arctic',
    name: 'Gates of the Arctic',
    state: 'Alaska',
    region: 'Alaska',
    shortDescription: 'Trackless tundra, mountain passes, and wild rivers above the Arctic Circle.',
    badgeTheme: 'blue',
    status: 'in-progress',
    futureSlug: 'gates-of-the-arctic',
  },
  {
    id: 'gateway-arch',
    name: 'Gateway Arch',
    state: 'Missouri',
    region: 'Midwest',
    shortDescription: 'A riverfront monument and civic landscape marking westward expansion at St. Louis.',
    badgeTheme: 'blue',
    status: 'in-progress',
    futureSlug: 'gateway-arch',
  },
  {
    id: 'glacier',
    name: 'Glacier',
    state: 'Montana',
    region: 'Mountain West',
    shortDescription: 'Alpine lakes, glacial valleys, and dramatic ridgelines on the northern Rockies spine.',
    badgeTheme: 'green',
    status: 'in-progress',
    futureSlug: 'glacier',
  },
  {
    id: 'glacier-bay',
    name: 'Glacier Bay',
    state: 'Alaska',
    region: 'Alaska',
    shortDescription: 'Tidewater glaciers, icy fjords, and forested islands along Alaskas southeastern coast.',
    badgeTheme: 'blue',
    status: 'in-progress',
    futureSlug: 'glacier-bay',
  },
  {
    id: 'grand-canyon',
    name: 'Grand Canyon',
    state: 'Arizona',
    region: 'Southwest',
    shortDescription: 'Layered canyon walls and river depth revealing one of Earths grandest geologic stories.',
    badgeTheme: 'red',
    status: 'in-progress',
    futureSlug: 'grand-canyon',
  },
  {
    id: 'grand-teton',
    name: 'Grand Teton',
    state: 'Wyoming',
    region: 'Mountain West',
    shortDescription: 'Jagged peaks, sage flats, and reflective lakes beneath the Teton Range.',
    badgeTheme: 'green',
    status: 'in-progress',
    futureSlug: 'grand-teton',
  },
  {
    id: 'great-basin',
    name: 'Great Basin',
    state: 'Nevada',
    region: 'Great Basin',
    shortDescription: 'Ancient bristlecones, limestone caves, and high desert peaks under dark western skies.',
    badgeTheme: 'green',
    status: 'in-progress',
    futureSlug: 'great-basin',
  },
  {
    id: 'great-sand-dunes',
    name: 'Great Sand Dunes',
    state: 'Colorado',
    region: 'Mountain West',
    shortDescription: 'Towering dunes rise against alpine backdrops, wetlands, and broad San Luis light.',
    badgeTheme: 'red',
    status: 'in-progress',
    futureSlug: 'great-sand-dunes',
  },
  {
    id: 'great-smoky-mountains',
    name: 'Great Smoky Mountains',
    state: 'Tennessee, North Carolina',
    region: 'Southeast',
    shortDescription: 'Blue ridges, old-growth forests, and mist-softened hollows along the Appalachian crest.',
    badgeTheme: 'green',
    status: 'in-progress',
    futureSlug: 'great-smoky-mountains',
  },
  {
    id: 'guadalupe-mountains',
    name: 'Guadalupe Mountains',
    state: 'Texas',
    region: 'Southwest',
    shortDescription: 'Fossil reefs, desert trails, and high Texas peaks rising from the Chihuahuan Basin.',
    badgeTheme: 'red',
    status: 'in-progress',
    futureSlug: 'guadalupe-mountains',
  },
  {
    id: 'haleakala',
    name: 'Haleakala',
    state: 'Hawaii',
    region: 'Hawaii',
    shortDescription: 'Volcanic summit landscapes and rainforest coast woven together on the island of Maui.',
    badgeTheme: 'red',
    status: 'in-progress',
    futureSlug: 'haleakala',
  },
  {
    id: 'hawaii-volcanoes',
    name: 'Hawaii Volcanoes',
    state: 'Hawaii',
    region: 'Hawaii',
    shortDescription: 'Lava fields, crater rims, and active volcanic forces shaping the Big Island.',
    badgeTheme: 'red',
    status: 'in-progress',
    futureSlug: 'hawaii-volcanoes',
  },
  {
    id: 'hot-springs',
    name: 'Hot Springs',
    state: 'Arkansas',
    region: 'South',
    shortDescription: 'Historic bathhouses and thermal springs set against forested hills in central Arkansas.',
    badgeTheme: 'blue',
    status: 'in-progress',
    futureSlug: 'hot-springs',
  },
  {
    id: 'indiana-dunes',
    name: 'Indiana Dunes',
    state: 'Indiana',
    region: 'Midwest',
    shortDescription: 'Lake Michigan shore, shifting dunes, and rich habitat packed into a narrow coast.',
    badgeTheme: 'blue',
    status: 'in-progress',
    futureSlug: 'indiana-dunes',
  },
  {
    id: 'isle-royale',
    name: 'Isle Royale',
    state: 'Michigan',
    region: 'Great Lakes',
    shortDescription: 'Remote island wilderness, inland lakes, and long trails deep in Lake Superior.',
    badgeTheme: 'blue',
    status: 'in-progress',
    futureSlug: 'isle-royale',
  },
  {
    id: 'joshua-tree',
    name: 'Joshua Tree',
    state: 'California',
    region: 'Southwest',
    shortDescription: 'Boulder piles, desert trees, and stark sky where the Mojave meets the Colorado.',
    badgeTheme: 'red',
    status: 'in-progress',
    futureSlug: 'joshua-tree',
  },
  {
    id: 'katmai',
    name: 'Katmai',
    state: 'Alaska',
    region: 'Alaska',
    shortDescription: 'Brown bears, volcanic valleys, and salmon-rich rivers on Alaskas wild coast.',
    badgeTheme: 'green',
    status: 'in-progress',
    futureSlug: 'katmai',
  },
  {
    id: 'kenai-fjords',
    name: 'Kenai Fjords',
    state: 'Alaska',
    region: 'Alaska',
    shortDescription: 'Glacier-fed fjords, marine wildlife, and icefields pressing toward the sea.',
    badgeTheme: 'blue',
    status: 'in-progress',
    futureSlug: 'kenai-fjords',
  },
  {
    id: 'kings-canyon',
    name: 'Kings Canyon',
    state: 'California',
    region: 'West',
    shortDescription: 'Deep canyon walls, giant sequoias, and high Sierra country beyond the foothills.',
    badgeTheme: 'green',
    status: 'in-progress',
    futureSlug: 'kings-canyon',
  },
  {
    id: 'kobuk-valley',
    name: 'Kobuk Valley',
    state: 'Alaska',
    region: 'Alaska',
    shortDescription: 'Arctic dunes, winding rivers, and caribou migration across a roadless northern valley.',
    badgeTheme: 'blue',
    status: 'in-progress',
    futureSlug: 'kobuk-valley',
  },
  {
    id: 'lake-clark',
    name: 'Lake Clark',
    state: 'Alaska',
    region: 'Alaska',
    shortDescription: 'Volcanoes, salmon streams, and vast lakes joining coast, tundra, and mountains.',
    badgeTheme: 'blue',
    status: 'in-progress',
    futureSlug: 'lake-clark',
  },
  {
    id: 'lassen-volcanic',
    name: 'Lassen Volcanic',
    state: 'California',
    region: 'West',
    shortDescription: 'Steam vents, cinder cones, and alpine forests clustered around an active volcanic field.',
    badgeTheme: 'red',
    status: 'in-progress',
    futureSlug: 'lassen-volcanic',
  },
  {
    id: 'mammoth-cave',
    name: 'Mammoth Cave',
    state: 'Kentucky',
    region: 'Southeast',
    shortDescription: 'Long cave passages and green river hills shelter the worlds longest known cave.',
    badgeTheme: 'blue',
    status: 'in-progress',
    futureSlug: 'mammoth-cave',
  },
  {
    id: 'mesa-verde',
    name: 'Mesa Verde',
    state: 'Colorado',
    region: 'Southwest',
    shortDescription: 'Cliff dwellings and mesa-top sites preserving centuries of Ancestral Pueblo history.',
    badgeTheme: 'red',
    status: 'in-progress',
    futureSlug: 'mesa-verde',
  },
  {
    id: 'mount-rainier',
    name: 'Mount Rainier',
    state: 'Washington',
    region: 'Pacific Northwest',
    shortDescription: 'Glacier slopes, wildflower meadows, and a singular stratovolcano dominating the horizon.',
    badgeTheme: 'green',
    status: 'in-progress',
    futureSlug: 'mount-rainier',
  },
  {
    id: 'new-river-gorge',
    name: 'New River Gorge',
    state: 'West Virginia',
    region: 'Appalachia',
    shortDescription: 'Deep forested gorge, sandstone cliffs, and a free-flowing river through southern West Virginia.',
    badgeTheme: 'green',
    status: 'in-progress',
    futureSlug: 'new-river-gorge',
  },
  {
    id: 'north-cascades',
    name: 'North Cascades',
    state: 'Washington',
    region: 'Pacific Northwest',
    shortDescription: 'Jagged summits, glaciers, and dense evergreen valleys across Washingtons northern range.',
    badgeTheme: 'green',
    status: 'in-progress',
    futureSlug: 'north-cascades',
  },
  {
    id: 'olympic',
    name: 'Olympic',
    state: 'Washington',
    region: 'Pacific Northwest',
    shortDescription: 'Rainforest, glacier-capped mountains, and wild Pacific beaches on one peninsula.',
    badgeTheme: 'green',
    status: 'in-progress',
    futureSlug: 'olympic',
  },
  {
    id: 'petrified-forest',
    name: 'Petrified Forest',
    state: 'Arizona',
    region: 'Southwest',
    shortDescription: 'Painted Desert color and ancient fossil logs scattered across open high desert.',
    badgeTheme: 'red',
    status: 'in-progress',
    futureSlug: 'petrified-forest',
  },
  {
    id: 'pinnacles',
    name: 'Pinnacles',
    state: 'California',
    region: 'West',
    shortDescription: 'Spired volcanic rock, chaparral hills, and condor country in inland California.',
    badgeTheme: 'red',
    status: 'in-progress',
    futureSlug: 'pinnacles',
  },
  {
    id: 'redwood',
    name: 'Redwood',
    state: 'California',
    region: 'Pacific Coast',
    shortDescription: 'Towering redwoods, fern canyons, and fog-softened coast along northern California.',
    badgeTheme: 'green',
    status: 'in-progress',
    futureSlug: 'redwood',
  },
  {
    id: 'rocky-mountain',
    name: 'Rocky Mountain',
    state: 'Colorado',
    region: 'Mountain West',
    shortDescription: 'Alpine tundra, high lakes, and sweeping ridgelines across the central Rockies.',
    badgeTheme: 'green',
    status: 'in-progress',
    futureSlug: 'rocky-mountain',
  },
  {
    id: 'saguaro',
    name: 'Saguaro',
    state: 'Arizona',
    region: 'Southwest',
    shortDescription: 'Iconic cactus forests and Sonoran desert light framing the edges of Tucson.',
    badgeTheme: 'red',
    status: 'in-progress',
    futureSlug: 'saguaro',
  },
  {
    id: 'sequoia',
    name: 'Sequoia',
    state: 'California',
    region: 'West',
    shortDescription: 'Massive trees, granite country, and high Sierra wilderness beyond giant groves.',
    badgeTheme: 'green',
    status: 'in-progress',
    futureSlug: 'sequoia',
  },
  {
    id: 'shenandoah',
    name: 'Shenandoah',
    state: 'Virginia',
    region: 'Appalachia',
    shortDescription: 'Blue Ridge overlooks, wooded hollows, and long skyline drives above the valley.',
    badgeTheme: 'green',
    status: 'in-progress',
    futureSlug: 'shenandoah',
  },
  {
    id: 'theodore-roosevelt',
    name: 'Theodore Roosevelt',
    state: 'North Dakota',
    region: 'Great Plains',
    shortDescription: 'Badlands, prairie, and bison country honoring a president shaped by this landscape.',
    badgeTheme: 'red',
    status: 'in-progress',
    futureSlug: 'theodore-roosevelt',
  },
  {
    id: 'virgin-islands',
    name: 'Virgin Islands',
    state: 'U.S. Virgin Islands',
    region: 'Caribbean',
    shortDescription: 'White-sand bays, coral waters, and tropical hills across St. John and St. Thomas.',
    badgeTheme: 'blue',
    status: 'in-progress',
    futureSlug: 'virgin-islands',
  },
  {
    id: 'voyageurs',
    name: 'Voyageurs',
    state: 'Minnesota',
    region: 'Great Lakes',
    shortDescription: 'Island-dotted lakes, boreal forest, and canoe routes along the northern border.',
    badgeTheme: 'blue',
    status: 'in-progress',
    futureSlug: 'voyageurs',
  },
  {
    id: 'white-sands',
    name: 'White Sands',
    state: 'New Mexico',
    region: 'Southwest',
    shortDescription: 'Brilliant gypsum dunes rolling in white waves across a broad desert basin.',
    badgeTheme: 'blue',
    status: 'in-progress',
    futureSlug: 'white-sands',
  },
  {
    id: 'wind-cave',
    name: 'Wind Cave',
    state: 'South Dakota',
    region: 'Great Plains',
    shortDescription: 'Mixed-grass prairie above and intricate cave passage below in the Black Hills.',
    badgeTheme: 'green',
    status: 'in-progress',
    futureSlug: 'wind-cave',
  },
  {
    id: 'wrangell-st-elias',
    name: 'Wrangell-St. Elias',
    state: 'Alaska',
    region: 'Alaska',
    shortDescription: 'Immense glaciers, giant peaks, and raw scale across Americas largest national park.',
    badgeTheme: 'blue',
    status: 'in-progress',
    futureSlug: 'wrangell-st-elias',
  },
  {
    id: 'zion',
    name: 'Zion',
    state: 'Utah',
    region: 'Southwest',
    shortDescription: 'Sheer canyon walls, hanging gardens, and desert river pathways in southern Utah.',
    badgeTheme: 'red',
    status: 'in-progress',
    futureSlug: 'zion',
  },
];

const PARKS = PARK_DEFINITIONS.map(makePark);
